---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc
  namespace: {{ .Release.Namespace }}
  labels:
    app: vdc
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  replicas: 1
  selector:
    matchLabels:
      app: vdc
  template:
    metadata:
      name: vdc
      labels:
        app: vdc
    spec:
      serviceAccountName: default-editor
      containers:
        - name: vdc
          image: "{{ .Values.vdc.image.repository }}:{{ .Values.vdc.image.tag }}"
          imagePullPolicy: {{ .Values.vdc.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: MONGODB_URI
              value: "mongodb://vdc-mongodb:27017/"
            - name: MONGODB_DATABASE
              value: "vision_dataset_curation"
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootUser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootPassword
            - name: PORT
              value: "5000"
            - name: HOST
              value: "0.0.0.0"
            - name: NAMESPACE
              value: {{ .Release.Namespace | quote }}
            - name: DOMAIN
              value: {{ .Values.domain | default "teknoir.dev" | quote }}
            - name: BASE_URL
              value: "/{{ .Release.Namespace }}/vision-dataset-curation"
          resources: {{- toYaml .Values.vdc.resources | nindent 12 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: vdc-mongodb
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  replicas: 1
  selector:
    matchLabels:
      app: vdc-mongodb
  template:
    metadata:
      name: vdc-mongodb
      labels:
        app: vdc-mongodb
    spec:
      containers:
        - name: vdc-mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootUser
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootPassword
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          resources: {{- toYaml .Values.mongodb.resources | nindent 12 }}
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: vdc-mongodb

{{- if .Values.mongoExpress.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdc-mongo-express
  namespace: {{ .Release.Namespace }}
  labels:
    app: vdc-mongo-express
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
  replicas: 1
  selector:
    matchLabels:
      app: vdc-mongo-express
  template:
    metadata:
      name: vdc-mongo-express
      labels:
        app: vdc-mongo-express
    spec:
      containers:
        - name: vdc-mongo-express
          image: "{{ .Values.mongoExpress.image.repository }}:{{ .Values.mongoExpress.image.tag }}"
          imagePullPolicy: {{ .Values.mongoExpress.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootUser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootPassword
            - name: ME_CONFIG_MONGODB_SERVER
              value: vdc-mongodb
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"
            - name: ME_CONFIG_SITE_BASEURL
              value: "/"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootUser
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vdc-mongodb-secret
                  key: rootPassword
            - name: ME_CONFIG_OPTIONS_EDITORTHEME
              value: "dark"
          resources: {{- toYaml .Values.mongoExpress.resources | nindent 12 }}
{{- end }}
