---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdc-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: vdc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
