---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: vdc
  namespace: {{ .Release.Namespace }}
spec:
  gateways:
  - teknoir/teknoir-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /{{ .Release.Namespace }}/vision-dataset-curation
    route:
    - destination:
        host: vdc.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 80