apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-labeler-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-labeler-labeler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: auto-labeler-frontend
  template:
    metadata:
      labels:
        app: auto-labeler-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            - name: BASE_URL
              value: {{ include "auto-labeler-labeler.full-base-path" . | quote }}