{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auto-labeler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-labeler-labeler.labels" . | nindent 4 }}
  {{- if .Values.ingress.className }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | default "" | quote }}
      http:
        paths:
          - path: {{ .path | default "/" | quote }}
            pathType: Prefix
            backend:
              service:
                name: auto-labeler-frontend
                port:
                  number: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}
