---
apiVersion: v1
kind: Secret
metadata:
  name: auto-labeler-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-labeler-labeler.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.mongo.auth.username | quote }}
  password: {{ .Values.mongo.auth.password | quote }}
  uri: {{ printf "mongodb://%s:%s@auto-labeler-mongo:%.0f" .Values.mongo.auth.username .Values.mongo.auth.password .Values.mongo.service.port | quote }}
