apiVersion: v1
kind: Service
metadata:
  name: auto-labeler-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-labeler-labeler.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: auto-labeler-mongo
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.port }}
