---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-labeler-mongo
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auto-labeler-labeler.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
