mongo:
  image:
    repository: mongo
    tag: "8.0"
    pullPolicy: IfNotPresent
  auth:
    username: teknoir
    password: change-me
    existingSecret: ""
  service:
    port: 27017
  persistence:
    enabled: true
    size: 20Gi
    storageClass: ""
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

backend:
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/auto-labeler-backend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 8000
  env:
    mongoDatabase: auto_label_labeler
    gcsSignUrls: false
    gcsUrlTtlSeconds: 3600
    googleCredentialsPath: /var/secrets/google/key.json
  mongoSecretName: auto-labeler-mongo
  gcsServiceAccountKeySecret: ""
  gcsServiceAccountKey: ""
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraEnv: []

frontend:
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/auto-labeler-frontend
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    port: 80
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

ingress:
  enabled: false
  className: ""
  hosts: []
  tls: []

virtualService:
  enabled: true
  gateway: teknoir/teknoir-gateway
  hosts:
    - "*"
  basePath: /auto-labeler-labeler

commonLabels: {}
